# Generated by Django 5.0.6 on 2024-06-22 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Request',
            fields=[
                ('eq_name', models.CharField(max_length=100)),
                ('eq_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Network Devices', 'Network devices'), ('Peripherals', 'Peripherals')], max_length=100)),
                ('department', models.CharField(choices=[('Human Resources (HR)', 'Human resources (hr)'), ('Finance/Accounting', 'Finance/accounting'), ('Information Technology (IT)', 'Information technology (it)'), ('Marketing/Sales', 'Marketing/sales'), ('Operations', 'Operations'), ('Engineering', 'Engineering')], max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.CharField(choices=[('Account Creation/Deletion', 'Account creation/deletion'), ('Password Reset/Unlock', 'Password reset/unlock'), ('Server Access', 'Server access'), ('Application Installation', 'Application installation'), ('Troubleshoot', 'Troubleshoot'), ('Security Incident Report', 'Security incident report'), ('Data Backup/Recovery', 'Data backup/recovery'), ('Hardware Installation', 'Hardware installation'), ('Network', 'Network')], max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Waiting', max_length=100)),
                ('upload', models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
