# Generated by Django 5.0.6 on 2024-06-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Closed_By_Employee', 'Closed_by_employee'), ('Closed_By_Admin', 'Closed_by_admin')], default='Waiting', max_length=100),
        ),
    ]
