# Generated by Django 5.0.6 on 2024-06-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_it_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled_By_Employee', 'Cancelled_by_employee'), ('Cancelled_By_Admin', 'Cancelled_by_admin'), ('Closed_By_Employee', 'Closed_by_employee'), ('Closed_By_Admin', 'Closed_by_admin')], default='Waiting', max_length=100),
        ),
    ]
