# Generated by Django 5.0.6 on 2024-06-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_it_request_eq_type_alter_it_request_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
