# Generated by Django 5.0.6 on 2024-06-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_it_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='issue',
            field=models.CharField(choices=[('Account Creation/Deletion', 'Account creation/deletion'), ('Password Reset/Unlock', 'Password reset/unlock'), ('Server Access', 'Server access'), ('Application Installation', 'Application installation'), ('Troubleshoot', 'Troubleshoot'), ('Security Incident Report', 'Security incident report'), ('Data Backup/Recovery', 'Data backup/recovery'), ('Hardware Installation', 'Hardware installation'), ('Network', 'Network')], default='Account Creation/Deletion', max_length=100),
        ),
    ]
