# Generated by Django 5.0.6 on 2024-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_it_request_eq_type_alter_it_request_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='it_request',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
