# Generated by Django 5.0.6 on 2024-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_it_request_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='eq_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Network Devices', 'Network devices'), ('Peripherals', 'Peripherals')], max_length=100),
        ),
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In progress'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
