# Generated by Django 5.0.6 on 2024-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_it_request_eq_type_alter_it_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
    ]
