# Generated by Django 5.0.6 on 2024-06-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_it_request_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='<str:username>/user_screenshots/'),
        ),
    ]
