# Generated by Django 5.0.6 on 2024-06-08 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_it_request_screenshot_it_request_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_request',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
